-- Create the ativos table
CREATE TABLE IF NOT EXISTS ativos (
  id_ativo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_condominio BIGINT NOT NULL REFERENCES condominios(id_comdominio) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  categoria TEXT NOT NULL,
  marca TEXT,
  modelo TEXT,
  num_serie NUMERIC,
  data_instalacao DATE,
  estado TEXT CHECK (estado IN ('excelente', 'bom', 'regular', 'mau')),
  descricao TEXT,
  valor NUMERIC(10, 2),
  localizacao TEXT,
  observacoes TEXT,
  data_proxima_manutencao DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE ativos ENABLE ROW LEVEL SECURITY;

-- Create policies (adjust as needed for your auth setup)
-- Allow authenticated users to view all ativos (or filter by condominio access if you have that logic)
CREATE POLICY "Allow authenticated users to select ativos" ON ativos
  FOR SELECT TO authenticated USING (true);

-- Allow authenticated users to insert ativos
CREATE POLICY "Allow authenticated users to insert ativos" ON ativos
  FOR INSERT TO authenticated WITH CHECK (true);

-- Allow authenticated users to update ativos
CREATE POLICY "Allow authenticated users to update ativos" ON ativos
  FOR UPDATE TO authenticated USING (true);

-- Allow authenticated users to delete ativos
CREATE POLICY "Allow authenticated users to delete ativos" ON ativos
  FOR DELETE TO authenticated USING (true);
