-- Add missing columns to condominios table
ALTER TABLE condominios
ADD COLUMN IF NOT EXISTS iban TEXT,
ADD COLUMN IF NOT EXISTS banco TEXT,
ADD COLUMN IF NOT EXISTS num_fracoes INTEGER,
ADD COLUMN IF NOT EXISTS num_pisos INTEGER,
ADD COLUMN IF NOT EXISTS ano_construcao INTEGER,
ADD COLUMN IF NOT EXISTS tem_elevador BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS email_geral TEXT,
ADD COLUMN IF NOT EXISTS telefone TEXT,
ADD COLUMN IF NOT EXISTS admin_externa BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS apolice_seguro TEXT,
ADD COLUMN IF NOT EXISTS companhia_seguro TEXT;
